[package]
name = "project-lexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "lexer"
crate-type = ["cdylib"]

[dependencies]
clex = "0.1.0"
pyo3 = "0.20.0"
